import { requirePermission } from "@/lib/auth/access";
import { PermissionDenied } from "@/components/data-display/page-state";
import { StatusBadge } from "@/components/data-display/status-badge";
import { PageHeader } from "@/components/layout/page-header";
import {
  BaseClassFeesForm,
  FlatFeesForm,
  TransportChargesForm,
} from "@/features/finance/components/fee-rate-forms";
import {
  FinanceCategoryForm,
  PaymentMethodForm,
} from "@/features/finance/components/category-forms";
import { getFinanceSettings } from "@/features/finance/server/queries";

export default async function FinancialSettingsPage() {
  const context = await requirePermission("finance.settings.manage");
  if (!context) return <PermissionDenied />;
  const settings = await getFinanceSettings();

  return (
    <>
      <PageHeader
        title="Financial settings"
        description={`Configure fee amounts, payment methods, and income/expense categories for ${settings.academicYearName} ${settings.academicTermName}. Changing these values never rewrites an already-issued invoice.`}
      />
      <div className="space-y-5">
        <BaseClassFeesForm
          academicYearId={settings.academicYearId}
          academicTermId={settings.academicTermId}
          rows={settings.baseClassFees}
        />
        <TransportChargesForm
          academicYearId={settings.academicYearId}
          academicTermId={settings.academicTermId}
          rows={settings.transportCharges}
        />
        <FlatFeesForm
          academicYearId={settings.academicYearId}
          academicTermId={settings.academicTermId}
          flatFees={settings.flatFees}
        />

        <section
          className="panel border-dashed p-5"
          aria-labelledby="numbering-title"
        >
          <h2 id="numbering-title" className="text-sm font-semibold">
            Document numbering
          </h2>
          <p className="mt-1 text-sm text-muted-foreground">
            Invoice, payment, receipt, expense and reversal numbers are
            generated by the server and are always unique. Gaps are allowed so
            retry-safe numbering is never weakened to force a gapless sequence.
          </p>
          <dl className="mt-4 grid grid-cols-2 gap-x-6 gap-y-3 sm:grid-cols-3 lg:grid-cols-5">
            {[
              ["Invoice", "BBA/INV/{YYYY}/{NNNNN}"],
              ["Payment", "BBA/PAY/{YYYY}/{NNNNN}"],
              ["Receipt", "BBA/RCT/{YYYY}/{NNNNN}"],
              ["Expense", "BBA/EXP/{YYYY}/{NNNNN}"],
              ["Reversal", "BBA/REV/{YYYY}/{NNNNN}"],
            ].map(([label, format]) => (
              <div key={label}>
                <dt className="text-xs text-muted-foreground">{label}</dt>
                <dd className="mt-1 font-mono text-xs font-semibold">
                  {format}
                </dd>
              </div>
            ))}
          </dl>
        </section>

        <section className="panel p-5" aria-labelledby="payment-methods-title">
          <div>
            <h2 id="payment-methods-title" className="text-base font-semibold">
              Payment methods
            </h2>
            <p className="mt-1 text-sm text-muted-foreground">
              Mobile Money and Bank Transfer require an external reference at
              the point of payment.
            </p>
          </div>
          <div className="mt-5 space-y-3">
            {settings.paymentMethods.map((method) => (
              <details key={method.id} className="configuration-disclosure">
                <summary>
                  <span>
                    <strong>{method.name}</strong>
                    <span className="ml-2 text-xs text-muted-foreground">
                      {method.code}
                    </span>
                  </span>
                  <StatusBadge
                    status={method.status === "active" ? "Active" : "Archived"}
                  />
                </summary>
                <div className="border-t border-border p-4">
                  <PaymentMethodForm record={method} />
                </div>
              </details>
            ))}
            <details className="configuration-disclosure">
              <summary>
                <strong>Add payment method</strong>
                <span className="text-xs text-muted-foreground">
                  Use when the school approves another payment method
                </span>
              </summary>
              <div className="border-t border-border p-4">
                <PaymentMethodForm />
              </div>
            </details>
          </div>
        </section>

        <section
          className="panel p-5"
          aria-labelledby="expense-categories-title"
        >
          <div>
            <h2
              id="expense-categories-title"
              className="text-base font-semibold"
            >
              Expense categories
            </h2>
            <p className="mt-1 text-sm text-muted-foreground">
              Every daily expense must use one of these configurable categories.
            </p>
          </div>
          <div className="mt-5 space-y-3">
            {settings.expenseCategories.map((category) => (
              <details key={category.id} className="configuration-disclosure">
                <summary>
                  <span>
                    <strong>{category.name}</strong>
                    <span className="ml-2 text-xs text-muted-foreground">
                      {category.code}
                    </span>
                  </span>
                  <StatusBadge
                    status={
                      category.status === "active" ? "Active" : "Archived"
                    }
                  />
                </summary>
                <div className="border-t border-border p-4">
                  <FinanceCategoryForm record={category} kind="expense" />
                </div>
              </details>
            ))}
            <details className="configuration-disclosure">
              <summary>
                <strong>Add expense category</strong>
                <span className="text-xs text-muted-foreground">
                  Use when the school approves another expense category
                </span>
              </summary>
              <div className="border-t border-border p-4">
                <FinanceCategoryForm kind="expense" />
              </div>
            </details>
          </div>
        </section>

        <section
          className="panel p-5"
          aria-labelledby="misc-income-categories-title"
        >
          <div>
            <h2
              id="misc-income-categories-title"
              className="text-base font-semibold"
            >
              Miscellaneous income categories
            </h2>
            <p className="mt-1 text-sm text-muted-foreground">
              Official categories remain a school decision; none are added until
              confirmed here.
            </p>
          </div>
          <div className="mt-5 space-y-3">
            {settings.miscIncomeCategories.length === 0 && (
              <p className="text-sm text-muted-foreground">
                No miscellaneous income categories are configured yet.
              </p>
            )}
            {settings.miscIncomeCategories.map((category) => (
              <details key={category.id} className="configuration-disclosure">
                <summary>
                  <span>
                    <strong>{category.name}</strong>
                    <span className="ml-2 text-xs text-muted-foreground">
                      {category.code}
                    </span>
                  </span>
                  <StatusBadge
                    status={
                      category.status === "active" ? "Active" : "Archived"
                    }
                  />
                </summary>
                <div className="border-t border-border p-4">
                  <FinanceCategoryForm record={category} kind="misc-income" />
                </div>
              </details>
            ))}
            <details className="configuration-disclosure">
              <summary>
                <strong>Add income category</strong>
                <span className="text-xs text-muted-foreground">
                  Use when the school approves another income category
                </span>
              </summary>
              <div className="border-t border-border p-4">
                <FinanceCategoryForm kind="misc-income" />
              </div>
            </details>
          </div>
        </section>
      </div>
    </>
  );
}
